use_frameworks!

platform :ios, '8.0'

target 'QFTBaiduSdk_Example' do
  pod 'QFTBaiduSdk', :path => '../'

  target 'QFTBaiduSdk_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
